---
- name: Install Apache2 on Alpine Linux
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  
  tasks:

    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present
       update_cache: false

    - name: Ensure httpd is enabled at and running now
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
